services:
  topo:
    image: xcord-topo
    ports:
      - "8090:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    group_add:
      - ${DOCKER_GID:-999}
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      Data__BasePath: /data
